import { abeezee } from "@/config/fonts";
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={abeezee.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
